name: SBOM Generation and Attestation

on:
  push:
    branches: [ "main" ]

jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     actions: read
     contents: write
     id-token: write
     attestations: write
     packages: write
    
   steps:
    - uses: actions/checkout@v3
    - uses: anchore/sbom-action@v0
      id: sbom
      with:
       format: spdx
       output-file: . 

    - uses: actions/attest-build-provenance@v2
      with:
       subject-path: ${{ env.ANCHORE_SBOM_ACTION_PRIOR_ARTIFACT }}
       
        
