name: SBOM Generation 

on:
  push:
    branches: [ "main" ]


jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     actions: read
     contents: write
   steps:
    - uses: actions/checkout@v3
    - uses: anchore/sbom-action@v0
   
