name: SBOM Generation and Attestation

on:
  push:
    branches: [ "main" ]

jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     actions: read
     contents: write
     id-token: write
     attestations: write
     packages: write
    
   steps:
    - uses: actions/checkout@v3
       
    # Step to generate a unique artifact name
    - name: Generate unique artifact name
      id: artifact
      run: |
            echo "ARTIFACT_NAME=sbom-$(date +%s)" >> $GITHUB_ENV
            sudo mkdir sbom 
    
    - uses: anchore/sbom-action@v0
      id: sbom
      with:
       format: spdx
       artifact-name: ${{ env.ARTIFACT_NAME }}
       output-file: sbom

       
    - uses: actions/attest-build-provenance@v2
      with:
       subject-path: ${{ env.ARTIFACT_NAME }}
       
        
